use kcbda_trusted;

CREATE EXTERNAL TABLE CLIENTES (
  ID_CLIENTE int,
  FC_NACIMIENTO date,
  DE_SEXO string,
  TELEFONO_CLIENTE bigint,
  TWITTER string,
  IP string
)
PARTITIONED by (DE_ESTADO string)
CLUSTERED BY (ID_CLIENTE) INTO 3 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY "|"
STORED AS ORC
LOCATION "/kcbda/TRUSTED/CLIENTES";

INSERT INTO TABLE CLIENTES PARTITION (DE_ESTADO)
SELECT
C.ID_CLIENTE,
C.FC_NACIMIENTO,
S.DE_SEXO,
C.TELEFONO_CLIENTE,
"@USER",
"XXX.XXX.XXX.XXX",
CE.DE_ESTADO
FROM kcbda_raw.ODS_HC_CLIENTES AS C
INNER JOIN kcbda_raw.ODS_DM_SEXOS S ON C.ID_SEXO = S.ID_SEXO
INNER JOIN kcbda_raw.ODS_HC_DIRECCIONES D ON C.ID_DIRECION_CLIENTE = D.ID_DIRECCION
INNER JOIN kcbda_raw.ODS_DM_CIUDADES_ESTADOS CE ON D.ID_CIUDAD_ESTADO = CE.ID_CIUDAD_ESTADO;


CREATE EXTERNAL TABLE FACTURAS (
  ID_FACTURA int,
  ID_CLIENTE int,
  CANTIDAD decimal(4,2),
  DE_METODO_PAGO string
)
PARTITIONED by (FC_PAGO_Y string, FC_PAGO_M string, FC_PAGO_D string)
CLUSTERED BY (ID_CLIENTE) INTO 3 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY "|"
STORED AS ORC
LOCATION "/kcbda/TRUSTED/FACTURAS";

INSERT INTO TABLE FACTURAS PARTITION (FC_PAGO_Y, FC_PAGO_M, FC_PAGO_D)
SELECT
F.ID_FACTURA,
F.ID_CLIENTE,
F.CANTIDAD,
MP.DE_METODO_PAGO,
YEAR(F.FC_PAGO) AS FC_PAGO_Y,
MONTH(F.FC_PAGO) AS FC_PAGO_M,
DAY(F.FC_PAGO) AS FC_PAGO_D
FROM kcbda_raw.ODS_HC_FACTURAS AS F
INNER JOIN kcbda_raw.ODS_DM_METODOS_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO;
